#!/usr/bin/env sh
# bundle.sh — flatten baton into one pasteable document.
#
#   ./bundle.sh              -> dist/baton-all.md      (every mode)
#   ./bundle.sh TEST         -> dist/baton-TEST.md     (one mode)
#
# Normally you paste the eleven-line invocation (prompt/invoke.md) and the
# agent reads these files off disk — cheaper, and it keeps the modes you are
# not running out of your context. Bundle only when the session can neither
# clone nor fetch: a locked-down environment, someone else's machine.
#
# Paste the bundle instead of the invocation, put your TARGET and MODE at the
# top, and skip the router's "Locate baton" step — everything it names is
# already inline below.

set -eu
here=$(cd "$(dirname "$0")" && pwd)
mode=${1:-ALL}
out="$here/dist/baton-$mode.md"
mkdir -p "$here/dist"

emit() { printf '\n\n<!-- ===== %s ===== -->\n\n' "$2" >> "$out"; cat "$1" >> "$out"; }

: > "$out"
{
  printf '# BATON v2 — bundled (%s)\n\n' "$mode"
  printf 'Generated by bundle.sh. Paste this entire document into a fresh session.\n'
  printf 'Because everything is inline, skip step 1 of the router (Locate baton) and\n'
  printf 'treat every file reference below as already loaded.\n'
} >> "$out"

emit "$here/prompt/baton.md"          "prompt/baton.md — THE ROUTER"
emit "$here/prompt/CONTRACT.md"       "prompt/CONTRACT.md"
emit "$here/personas/CONTRACT.md"     "personas/CONTRACT.md"

if [ "$mode" = "ALL" ]; then
  for f in "$here"/prompt/modes/*.md; do emit "$f" "prompt/modes/$(basename "$f")"; done
else
  f="$here/prompt/modes/$mode.md"
  [ -f "$f" ] || { echo "no such mode: $mode" >&2; echo "available: $(ls "$here"/prompt/modes | sed 's/\.md//' | tr '\n' ' ')" >&2; exit 1; }
  emit "$f" "prompt/modes/$mode.md"
fi

for f in "$here"/prompt/roles/*.md; do emit "$f" "prompt/roles/$(basename "$f")"; done

# Only the personas the selected mode actually seats. A mode's Seats table rows
# look like:  | `coverage-truth` | expert | AUDIT, VERIFY | ... |
if [ "$mode" = "ALL" ]; then
  for f in "$here"/personas/lenses/*.md; do emit "$f" "personas/lenses/$(basename "$f")"; done
  for f in "$here"/personas/users/*.md;  do emit "$f" "personas/users/$(basename "$f")"; done
else
  seats=$(sed -n '/^## Seats/,/^## Gates/p' "$here/prompt/modes/$mode.md" \
          | sed -E -n 's/^\| *`([a-z0-9-]+)` *\| *(expert|user) *\|.*/\2 \1/p')
  printf '%s\n' "$seats" | while read -r kind slug; do
    [ -n "${slug:-}" ] || continue
    case $kind in
      expert) f="$here/personas/lenses/$slug.md" ; d="personas/lenses/$slug.md" ;;
      user)   f="$here/personas/users/$slug.md"  ; d="personas/users/$slug.md" ;;
      *) continue ;;
    esac
    [ -f "$f" ] && emit "$f" "$d" || echo "warn: seat $slug has no file" >&2
  done
  printf '\n\n<!-- Seats not listed above keep their built-in lens definitions, which are\n'   >> "$out"
  printf '     the only ones this mode needs. To swap in a named roster, clone the repo\n'      >> "$out"
  printf '     and set PERSONAS: repo:<host/owner/name>. -->\n'                                 >> "$out"
fi

printf '\n%s: %s lines, %s bytes\n' "$out" "$(wc -l < "$out" | tr -d ' ')" "$(wc -c < "$out" | tr -d ' ')"
