#!/usr/bin/env sh
# bundle.sh — flatten baton into one pasteable document.
#
#   ./bundle.sh              -> dist/baton-all.md      (every mode)
#   ./bundle.sh TEST         -> dist/baton-TEST.md     (one mode)
#
# Normally you paste the eleven-line invocation (prompt/invoke.md) and the
# agent reads these files off disk — cheaper, and it keeps the modes you are
# not running out of your context. Bundle only when the session can neither
# clone nor fetch: a locked-down environment, someone else's machine.
#
# Paste the bundle instead of the invocation, put your TARGET and MODE at the
# top, and skip the router's "Locate baton" step — everything it names is
# already inline below.

set -eu
here=$(cd "$(dirname "$0")" && pwd)
mode=${1:-ALL}
out="$here/dist/baton-$mode.md"
mkdir -p "$here/dist"

emit() { printf '\n\n<!-- ===== %s ===== -->\n\n' "$2" >> "$out"; cat "$1" >> "$out"; }

: > "$out"
{
  printf '# BATON v6 — bundled (%s)\n\n' "$mode"
  printf 'Generated by bundle.sh. Paste this entire document into a fresh session.\n'
  printf 'Because everything is inline, skip step 1 of the router (Locate baton) and\n'
  printf 'treat every file reference below as already loaded.\n'
} >> "$out"

emit "$here/prompt/baton.md"          "prompt/baton.md — THE ROUTER"
emit "$here/prompt/CONTRACT.md"       "prompt/CONTRACT.md"
emit "$here/personas/CONTRACT.md"     "personas/CONTRACT.md"

# Every rule is its own file so there is exactly one place to amend it. They are
# concatenated here in section order, so the paste an agent receives is unchanged.
for pre in rule prule; do
  for f in $(ls "$here"/rules/$pre-*.md 2>/dev/null | sort -t- -k2,2n -k3,3n); do
    emit "$f" "rules/$(basename "$f")"
  done
done

if [ "$mode" = "ALL" ]; then
  for f in "$here"/prompt/modes/*.md; do emit "$f" "prompt/modes/$(basename "$f")"; done
else
  f="$here/prompt/modes/$mode.md"
  [ -f "$f" ] || { echo "no such mode: $mode" >&2; echo "available: $(ls "$here"/prompt/modes | sed 's/\.md//' | tr '\n' ' ')" >&2; exit 1; }
  emit "$f" "prompt/modes/$mode.md"
fi

for f in "$here"/prompt/roles/*.md; do emit "$f" "prompt/roles/$(basename "$f")"; done

# Only the user archetypes the selected mode drives. A mode's User archetypes table
# rows look like:  | `first-run` | user | PLAN, PROBE, VERIFY | ... |
# Expert lenses, luminaries, casting and panels were removed in v7.
if [ "$mode" = "ALL" ]; then
  for f in "$here"/personas/users/*.md; do emit "$f" "personas/users/$(basename "$f")"; done
else
  slugs=$(sed -n '/^## User archetypes/,/^## /p' "$here/prompt/modes/$mode.md" \
          | sed -E -n 's/^\| *`([a-z0-9-]+)` *\| *user *\|.*/\1/p')
  for slug in $slugs; do
    f="$here/personas/users/$slug.md"
    # A bundle missing an archetype silently runs short-handed, so refuse it.
    [ -f "$f" ] || { echo "error: mode $mode drives \`$slug\` but personas/users/$slug.md does not exist" >&2; exit 1; }
    emit "$f" "personas/users/$slug.md"
  done
fi

printf '\n%s: %s lines, %s bytes\n' "$out" "$(wc -l < "$out" | tr -d ' ')" "$(wc -c < "$out" | tr -d ' ')"
